  # SNS Topic for KVS Notifications
  KVSNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectName}-kvs-notifications-topic"
    
  # Policy to allow KVS to publish to SNS
  KVSNotificationTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref KVSNotificationTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: kinesisvideo.amazonaws.com
            Action: 'sns:Publish'
            Resource: !Ref KVSNotificationTopic
